services:
  djangochakra:
    build:
      context: ./chakra
      dockerfile: Dockerfile.dev
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    hostname: chakra
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    volumes:
      - ./chakra:/usr/src/chakra
 