# Generated by Django 5.1.5 on 2025-01-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('manager', 'Manager'), ('viewer', 'Viewer'), ('support_staff', 'Support_staff')], max_length=30),
        ),
    ]
