# Generated by Django 5.1.5 on 2025-01-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
