# Generated by Django 5.1.5 on 2025-02-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_ticket_updated_at_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
