# Generated by Django 5.1.5 on 2025-02-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_ticket_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deleted_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
