# Generated by Django 5.1.5 on 2025-02-03 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_log_ticket_alter_log_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.ticket'),
        ),
    ]
